<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    private function generateRandomCoffeeName() {
        $adjectives = array("Smooth", "Bold", "Rich", "Creamy", "Velvety", "Aromatic", "Mellow", "Exquisite", "Balanced", "Elegant");
        $nouns = array("Espresso", "Cappuccino", "Macchiato", "Mocha", "Latte", "Americano", "Affogato", "Ristretto", "Flat White", "Frappuccino");

        $randomAdjective = $adjectives[array_rand($adjectives)];
        $randomNoun = $nouns[array_rand($nouns)];

        $randomCoffeeName = $randomAdjective . " " . $randomNoun;

        return $randomCoffeeName;
    }

    private function generateRandomPrice() {
        $minPrice = 50000; // Harga minimal
        $maxPrice = 5000000; // Harga maksimal
        $priceRange = ($maxPrice - $minPrice) / 10000; // Jumlah rentang harga dengan kelipatan 10.000

        // Menghasilkan harga acak dengan kelipatan 10.000
        $randomNumber = rand(0, $priceRange);
        $randomPrice = ($randomNumber * 10000) + $minPrice;

        return $randomPrice;
    }

    private function getItems()
    {
        return [
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> "ABID CLEVER DRIPPER 102", 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> "ABID CLEVER DRIPPER 102", 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> "ABID CLEVER DRIPPER 102", 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> "Almond Biscuit", 
                "sub_title"=> "G COFFEE ROASTERY",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> "Aceh Gayo Coffee Beans", 
                "sub_title"=> "ANOMALI COFFEE",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> "Blackpearl Coffee Beans", 
                "sub_title"=> "ANOMALI COFFEE",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> "BOKASSO #3", 
                "sub_title"=> "TITIK TEMU ROASTERY",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> "Ciwidey West Java", 
                "sub_title"=> "REIROM COFFEE SOLUTION",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> "Espresso Blend - Kungfu Kicks", 
                "sub_title"=> "G COFFEE ROASTERY",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> "Espresso Blend 1.0 - 200 gr", 
                "sub_title"=> "REIROM COFFEE SOLUTION",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "IRENK BEANS",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "ANOMALI COFFEE",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
            [
                "origin_id"=> rand(1, 6), 
                "species_id"=> rand(1, 3), 
                "roast_level_id"=> rand(1, 4), 
                "tasted_id"=> rand(1, 6), 
                "processing_id"=> rand(1, 4),
                "title"=> $this->generateRandomCoffeeName(), 
                "sub_title"=> "UBRUKKOPI",
                "stock"=> rand(55, 555),
                "price"=> $this->generateRandomPrice(),
                "rating"=> rand(1, 100),
                "filename" => null,
                "filepath" => null,
                "description"=> null,
                "information"=> null
            ],
        ];
    }

    public function run()
    {
        foreach ($this->getItems() as $value) {
            $findData = Product::where('title', $value['title'])->first();
            if (blank($findData)) {
                 $createData = Product::create([
                    "origin_id" => $value['origin_id'],
                    "species_id" => $value['species_id'],
                    "roast_level_id" => $value['roast_level_id'],
                    "tasted_id" => $value['tasted_id'],
                    "processing_id" => $value['processing_id'],
                    "title" => $value['title'],
                    "sub_title" => $value['sub_title'],
                    "stock" => $value['stock'],
                    "price" => $value['price'],
                    "rating" => $value['rating'],
                    "filename"  => $value['filename'],
                    "filepath"  => $value['filepath'],
                    "description" => $value['description'],
                    "information" => $value['information']
                ]);
            }
        }
    }
}
